# -*- coding: utf-8 -*-
"""drop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9hI80SDffWH60rkBT8UDVcpPR_KiPl0
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten, Dropout
(x_train, y_train), (x_test, y_test) = mnist.load_data()  # загрузка выборки
x_train = x_train / 255 # нормализация
x_test = x_test / 255
y_train_cat = keras.utils.to_categorical(y_train, 10) # приведение к вектору из 0 и 1 (10 - размерность)
y_test_cat = keras.utils.to_categorical(y_test, 10)

#Уменьшим число начальных данных
limit=4000
kn=10
x_train_data=x_train[:limit]
y_train_data=y_train_cat[:limit]

x_valid=x_train[limit:limit*2]
y_valid=y_train_cat[limit:limit*2]

model = keras.Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(kn , activation='relu'),
    Dense(10, activation='softmax') ])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
print('обучение')
his=model.fit(x_train_data, y_train_data,   epochs=50,batch_size=32, validation_data=(x_valid, y_valid),verbose=False )
model.evaluate(x_test, y_test_cat,verbose=False )
# Метод evaluate прогоняет все тестовое множество и вычисляет значение критерия качества и метрики
plt.plot(his.history['loss'])
plt.plot(his.history['val_loss'])
plt.show()

# выделение неверных результатов
pred = model.predict(x_test)
pred = np.argmax(pred, axis=1)

mask = pred == y_test
# подсчет ошибок
er=0
for k in mask:
   if k==0:
       er+=1
print('kn=', kn,'  limit=', limit,'  k-vo  error ', er)

"""Увеличим число нейронов

"""

kn=300
model = keras.Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(kn , activation='relu'),
    Dense(10, activation='softmax') ])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
print('обучение')
his=model.fit(x_train_data, y_train_data,   epochs=50,batch_size=32, validation_data=(x_valid, y_valid),verbose=False )
model.evaluate(x_test, y_test_cat,verbose=False )
# Метод evaluate прогоняет все тестовое множество и вычисляет значение критерия качества и метрики
plt.plot(his.history['loss'])
plt.plot(his.history['val_loss'])
plt.show()

pred = model.predict(x_test)
pred = np.argmax(pred, axis=1)
mask = pred == y_test
er=0
for k in mask:
   if k==0:
       er+=1
print('kn=', kn,'  limit=', limit,'  k-vo  error ', er)

"""Добавим dropout

"""

drop=0.9
model = keras.Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(kn , activation='relu'),
    Dropout(drop),
    Dense(10, activation='softmax') ])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
print('обучение')
his=model.fit(x_train_data, y_train_data,   epochs=100,batch_size=32, validation_data=(x_valid, y_valid),verbose=False )
model.evaluate(x_test, y_test_cat,verbose=False )
# Метод evaluate прогоняет все тестовое множество и вычисляет значение критерия качества и метрики
plt.plot(his.history['loss'])  # синий график
plt.plot(his.history['val_loss']) # бежевый график
plt.show()

pred = model.predict(x_test)
pred = np.argmax(pred, axis=1)
mask = pred == y_test
er=0
for k in mask:
   if k==0:
       er+=1
print('kn=', kn,'  limit=', limit, 'drop= ', drop,'  k-vo  error ', er)